Paths :
  basepath : "/mnt/merged/emeitz/cv_test"
  ucposcar_path : "/home/emeitz/scripts/TDEP/SW/infile.ucposcar2"
  ssposcar_path : "/home/emeitz/scripts/TDEP/tdep_free_energy_cv/data/structures/SW/infile.ssposcar"
  ifc_path : "/mnt/merged/emeitz/SW_IFC_INTERPOLATION_NODES/IFCs"
HeatCapFreeEnergyParams:
  temperatures : [100,300,500,700,900,1100,1300]
  dT : 0.5
  k_mesh : [30, 30, 30]
  n_cores : 40
  fd_stencil_size : 3
  interp_settings :   
    temps_to_interpolate : [] # can leave empty, will be automatically calculated and overwritten
    n_cores_max : 40
    rc2 : 4.0
    rc3 : 4.0
    rc4 : 4.0
    make_ss_ifcs : True
    force_calc : "lammps"
    lds :
        time_step_fs : 1.0 
        infile_path : "/home/emeitz/scripts/TDEP/tdep_free_energy_cv/data/lammps_scripts/SW_silicon_dynamics.in"
        structure_path : "/home/emeitz/scripts/TDEP/tdep_free_energy_cv/data/structures/SW/initial_structure_SW_3UC.data"

        
