Paths :
  basepath : "/mnt/merged/emeitz/SW_IFC_INTERPOLATION_DATA"
  ucposcar_path : "/home/emeitz/scripts/TDEP/SW/infile.ucposcar2"
  ssposcar_path : "/home/emeitz/scripts/TDEP/tdep_free_energy_cv/data/structures/SW/infile.ssposcar"
IFC_MD_Params:
    temperatures : [1300]
    n_cores_max : 40
    rc2 : 4.0
    rc3 : 4.0
    rc4 : 4.0
    lds :
        time_step_fs : 1.0 
        infile_path : "/home/emeitz/scripts/TDEP/tdep_free_energy_cv/data/lammps_scripts/SW_silicon_dynamics.in"
        structure_path : "/home/emeitz/scripts/TDEP/tdep_free_energy_cv/data/structures/SW/initial_structure_SW_3UC.data"
        n_cores : 4
        data_interval : 5000
        n_configs : 25
    

#[75, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150, 1200, 1250, 1300, 1350]